version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: s2o_mysql
    restart: always
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: s2o_database
      MYSQL_USER: s2o_user
      MYSQL_PASSWORD: s2o_password
      MYSQL_ROOT_PASSWORD: rootpassword
    volumes:
      - db_data:/var/lib/mysql

  s2o_app:
    image: rifathmfm/s2o-backend:latest # Replace with your actual image
    container_name: s2o_springboot_app
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/s2o_database
      SPRING_DATASOURCE_USERNAME: s2o_user
      SPRING_DATASOURCE_PASSWORD: s2o_password
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_SHOW_SQL: "true"