version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: s2o_mysql
    restart: always
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: s2o_database
      MYSQL_USER: s2o_user
      MYSQL_PASSWORD: s2o_password
      MYSQL_ROOT_PASSWORD: rootpassword
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: